ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get update && \
    apt-get install -y ros-humble-joint-state-publisher-gui \
    ros-humble-xacro ros-humble-velodyne libusb-dev libusb-1.0-0-dev \
    ros-humble-pcl-ros ros-humble-vision-msgs && \
    rm -rf /var/lib/apt/lists

RUN git clone https://github.com/PointCloudLibrary/pcl.git -b pcl-1.12.1 pcl && \
    cd pcl && mkdir build && cd build && \
    cmake .. && make -j8 && make install