ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get update && \
    apt-get install -y ros-humble-cudnn-cmake-module \
    ros-humble-tensorrt-cmake-module \
    ros-humlbe-geographic-msgs \
    ros-humble-osqp-vendor \
    ros-humble-point-cloud-msg-wrapper \
    libgeographic-dev geographiclib-tools \
    librange-v3-dev \
    ros-humble-tvm-vendor \
    libcpprest-dev \
    libfmt-dev \
    ros-humble-can-msgs \
    ros-humble-udp-msgs && \
    rm -rf /var/lib/apt/lists
