ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get update && \
    apt-get install -y libpcl-dev ros-humble-joint-state-publisher-gui \
    ros-humble-xacro ros-humble-velodyne \
    ros-humble-pcl-ros ros-humble-vision-msgs && \
    rm -rf /var/lib/apt/lists
