ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN pip install ultralytics lap

# RUN git clone --recursive --branch v0.14.0 https://github.com/pytorch/vision --depth 1 \
#     && cd vision \
#     && python3 setup.py install \
#     && cd .. && rm -r vision