ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get update && \
    apt-get install -y  \
    ripgrep ros-humble-foxglove-bridge ncdu fzf ros-humble-plotjuggler ros-humble-plotjuggler-ros && \
    rm -rf /var/lib/apt/lists