/**:
  ros__parameters:
    frequency: 100
    # init_pose: [-5.0, 5.0, 0.0] # x, y, psi
    # init_pose: [-63.0, -97.0, 3.1415] # x, y, psi
    init_pose: [0.0,0.0,0.0] # x, y, psi
    parent_frame: "odom"
    child_frame: "base_link"

# First Order Feedback Lineari  zation 1-DOF PID Controller for the VTec SDC1
sdc1_vel_pid_node:
  ros__parameters:
    Kp: 5.0
    Ki: 0.01
    Kd: 0.0 #0.01
    D_MAX: 180

# Stanley Controller Params
stanley_controller_node:
  ros__parameters:
    K: 1.0 # drives you to path faster, induces overshoot
    K_soft: 3.0 # softens overshoot
    DELTA_SAT: [0.467503, -0.309027] # radians